# Site settings
name: 凌晨四点半
email: jaypengfei@foxmail.com
author: 凌晨四点半
url: 
resume_site: 
github: https://github.com/jaypengfei/
baseurl: 
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: For you, a thousand times over.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: jaypengfei
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: 368737df426e7d6eb4b1bb7841394410

FB:
  comments :
    provider : yungentie
    duoshuo:
        short_name : jaypengfei
    disqus :
        short_name : jaypengfei
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light